### ISSUE TITLE
Business Ownership or Control Interest - Organization Enrollment

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#84]
When Business Ownership or Control Interest information is entered and submitted, FEIN info is wiped out, what is entered in the City field shifts to Zip Code field and Zip Code field info shifts to County field. Errors occur.

When all data is corrected the following error occurs:
Beneficial owner FEIN cannot exceed 9 characters.

Confirmed the FEIN is correct and does not exceed 9 characters. The field does not allow for more than the minimum, so this error is unnecessary.

Cannot move beyond this screen now.

**Comment by angied** [comment]
fixed.

**Comment by angied** [comment]
Reopening because this error is still occuring:

Beneficial owner FEIN cannot exceed 9 characters.

Confirmed the FEIN is correct and does not exceed 9 characters. The field does not allow for more than the minimum, so this error is unnecessary.

**Comment by alamora** [comment]
so you enter in 9 chars and see the error still?  Just want to make sure I understand.

Also, which system did you test this on?

**Comment by angied** [comment]
Yeah. It allows for a max of 9, and less than that clears the field completely.

The amazon link.

**Comment by cyberjag** [comment]
Angie, Did you clear browser cache before testing this? There might be a chance that your browser is still using the older cached javascript.

**Comment by angied** [comment]
Yes, I cleared cache and still got the error.

**Comment by alamora** [comment]
Should this issue now be resolved?

**Comment by angied** [comment]
Yes, this appears to be resolved.

**Comment by angied** [comment]
Reopening at request of Dan Tri because issue still occurs in http://mn-its-test.dhs.state.mn.us/cms/login.

**Comment by alamora** [comment]
Has the code from github been deployed to MN?

**Comment by angied** [comment]
Yes.

**Comment by alamora** [comment]
and browser cache was cleared?

**Comment by angied** [comment]
Yes.

**Comment by alamora** [comment]
_sigh_
Well, that's just odd because it's ok on the EC2 enviro.  We will take a look.

**Comment by angied** [comment]
Tested in mn environment, fixed.
